apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: python-world
  name: python-svc
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
      app: python-world
